
CREATE TABLE IF NOT EXISTS `User`(
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(255) NOT NULL UNIQUE,
    nickName VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    gold INT(11) NOT NULL DEFAULT(0),
    rankpoint INT(11) NOT NULL DEFAULT(0),
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);