services:
  game-server:
    image: hanwj75/myserver:game-server
    depends_on:
      - redis
      - mysql
    environment:
      HOST: game-server
      PORT: 3333
      # NGINX_HOST: game-server
      REDIS_HOST: redis
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: asdfg159
      ACCESS_TOKEN_SECRET_KEY: 'JWT_SECRET'
    ports:
      - '3333:3333'
    networks:
      - my-network
    command: ['sh', '-c', 'yarn migrate && yarn start']

  login-server:
    image: hanwj75/myserver:login-server
    depends_on:
      - redis
      - mysql
    environment:
      HOST: login-server
      PORT: 3334
      # NGINX_HOST: login-server
      REDIS_HOST: redis
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: asdfg159
      ACCESS_TOKEN_SECRET_KEY: 'JWT_SECRET'
    ports:
      - '3334:3334'
    networks:
      - my-network
    command: ['sh', '-c', 'yarn migrate && yarn api']

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: asdfg159
      MYSQL_DATABASE: USER_DB
      MYSQL_PASSWORD: asdfg159
    ports:
      - '55555:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - '11109:6379'
    networks:
      - my-network
  # nginx:
  #   image: nginx:stable-perl
  #   ports:
  #     - '80:80'
  #   networks:
  #     - my-network

networks:
  my-network:

volumes:
  mysql-data:
