export const PAYLOAD_ONEOF_CASE = 2;
export const VERSION_LENGTH = 1;
export const SEQUENCE = 4;
export const PAYLOAD_LENGTH = 4;

export const PACKET_TYPE = {
  // 회원가입 및 로그인
  REGISTER_REQUEST: 1,
  REGISTER_RESPONSE: 2,
  LOGIN_REQUEST: 3,
  LOGIN_RESPONSE: 4,

  // 방만들기 및 참여하기
  CREATE_ROOM_REQUEST: 5,
  CREATE_ROOM_RESPONSE: 6,
  GET_ROOMLIST_REQUEST: 7,
  GET_ROOMLIST_RESPONSE: 8,
  JOIN_ROOM_REQUEST: 9,
  JOIN_ROOM_RESPONSE: 10,
  JOIN_RANDOM_ROOM_REQUEST: 11,
  JOIN_RANDOM_ROOM_RESPONSE: 12,
  JOIN_ROOM_NOTIFICATION: 13,
  LEAVE_ROOM_REQUEST: 14,
  LEAVE_ROOM_RESPONSE: 15,
  LEAVE_ROOM_NOTIFICATION: 16,

  // 게임 시작
  GAME_PREPARE_REQUEST: 17,
  GAME_PREPARE_RESPONSE: 18,
  GAME_PREPARE_NOTIFICATION: 19,
  GAME_START_REQUEST: 20,
  GAME_START_RESPONSE: 21,
  GAME_START_NOTIFICATION: 22,

  // 위치 동기화
  POSITION_UPDATE_REQUEST: 23,
  POSITION_UPDATE_NOTIFICATION: 24,

  // 카드 사용
  USE_CARD_REQUEST: 25,
  USE_CARD_RESPONSE: 26,
  USE_CARD_NOTIFICATION: 27,
  CARD_EFFECT_NOTIFICATION: 29,

  // 유저 정보 업데이트
  USER_UPDATE_NOTIFICATION: 33,

  // 페이즈 업데이트
  PHASE_UPDATE_NOTIFITION: 34,
  PHASE_CHANGE_REQUEST: 47,
  //리액션
  REACTION_REQUEST: 35,
  REACTION_RESPONSE: 36,

  DESTROY_CARD_REQUEST: 37,
  DESTROY_CARD_RESPONSE: 38,
  DESTROY_CARD_RANDOM_REQUEST: 46,

  // 게임 종료 알림
  GAME_END_NOTIFICATION: 39,
};
